apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: pvc-backup-psp
  labels:
    app: stash
spec:
  privileged: false
  allowPrivilegeEscalation: false
  volumes:
  - "*"
  hostNetwork: false
  hostIPC: false
  hostPID: false
  runAsUser:
    rule: RunAsAny
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  fsGroup:
    rule: RunAsAny
---
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: update-status-psp
  labels:
    app: stash
spec:
  privileged: false
  allowPrivilegeEscalation: false
  volumes:
  - secret
  - emptyDir
  hostNetwork: false
  hostIPC: false
  hostPID: false
  runAsUser:
    rule: RunAsAny
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  fsGroup:
    rule: RunAsAny
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: demo-pvc-sa
  namespace: demo
  labels:
    app: stash
---
apiVersion: stash.appscode.com/v1beta1
kind: Function
metadata:
  name: pvc-backup
spec:
  image: appscodeci/stash:psp
  args:
  - backup-pvc
  - --provider=${REPOSITORY_PROVIDER}
  - --bucket=${REPOSITORY_BUCKET:=}
  - --endpoint=${REPOSITORY_ENDPOINT:=}
  - --path=${REPOSITORY_PREFIX:=}
  - --secret-dir=/etc/repository/secret # specified
  - --scratch-dir=/tmp/restic/scratch # specified
  - --hostname=${HOSTNAME}
  - --backup-dirs=${TARGET_DIRECTORIES}
  - --retention-keep-last=${RETENTION_KEEP_LAST:=0}
  - --retention-keep-hourly=${RETENTION_KEEP_HOURLY:=0}
  - --retention-keep-daily=${RETENTION_KEEP_DAILY:=0}
  - --retention-keep-weekly=${RETENTION_KEEP_WEEKLY:=0}
  - --retention-keep-monthly=${RETENTION_KEEP_MONTHLY:=0}
  - --retention-keep-yearly=${RETENTION_KEEP_YEARLY:=0}
  - --retention-keep-tags=${RETENTION_KEEP_TAGS:=}
  - --retention-prune=${RETENTION_PRUNE:=false}
  - --retention-dry-run=${RETENTION_DRY_RUN:=false}
  - --output-dir=${outputDir}
  #- --metrics-enabled
  #- --metrics-pushgateway-url
  #- --metrics-dir
  #- --metrics-labels
  volumeMounts:
  - name: ${scratchDirVolume}
    mountPath: /tmp/restic/scratch
  - name: ${targetVolume}
    mountPath: ${TARGET_MOUNT_PATH}
  - name: ${secretVolume}
    mountPath: /etc/repository/secret
  - name: ${outputVolume}
    mountPath: ${outputDir}
  podSecurityPolicyName: pvc-backup-psp
---
apiVersion: stash.appscode.com/v1beta1
kind: Function
metadata:
  name: update-status
spec:
  image: appscodeci/stash:psp
  args:
  - update-status
  - --namespace=${NAMESPACE="default"}
  - --repository=${REPOSITORY_NAME:=}
  - --backup-session=${BACKUP_SESSION:=}
  - --restore-session=${RESTORE_SESSION:=}
  - --output-dir=${outputDir}
  - --enable-status-subresource=${ENABLE_STATUS_SUBRESOURCE:=false}
  volumeMounts:
  - name: ${outputVolume}
    mountPath: ${outputDir}
  podSecurityPolicyName: update-status-psp
---
apiVersion: stash.appscode.com/v1beta1
kind: Task
metadata:
  name: pvc-backup
spec:
  steps:
  - name: pvc-backup
    params:
    - name: outputDir
      value: /tmp/backup # specified
    - name: scratchDirVolume
      value: scratch-volume # specified
    - name: targetVolume
      value: target-volume # specified
    - name: secretVolume
      value: secret-volume # specified
    - name: outputVolume
      value: output-volume # specified
  - name: update-status
    params:
    - name: outputDir
      value: /tmp/backup # specified
    - name: outputVolume
      value: output-volume # specified
  volumes:
    - name: target-volume
      persistentVolumeClaim:
        claimName: ${TARGET_NAME}
    - name: secret-volume
      secret:
        secretName: ${REPOSITORY_SECRET_NAME}
    - name: scratch-volume
      emptyDir: {}
    - name: output-volume
      emptyDir: {}
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: demo-pvc
  namespace: demo
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 256M
---
apiVersion: stash.appscode.com/v1beta1
kind: BackupConfiguration
metadata:
  name: demo-pvc-backup
  namespace: demo
spec:
  runtimeSettings:
    pod:
      serviceAccountName: demo-pvc-sa
  task:
    name: pvc-backup
  repository:
    name: local-repo
  schedule: "* * * * *"
  target:
    ref:
      apiVersion: v1
      kind: PersistentVolumeClaim
      name: demo-pvc
    volumeMounts:
    - name: source-data
      mountPath: /source/data
    directories:
    - /source/data
  retentionPolicy:
    keepLast: 5
    prune: true
