apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: default-backupsession-cron-psp
  labels:
    app: stash
spec:
  privileged: false
  allowPrivilegeEscalation: false
  hostNetwork: false
  hostIPC: false
  hostPID: false
  volumes:
  - secret # kubernetes mount service account token secret into the pod. so we need to give permission to mount secret volume
  runAsUser:
    rule: RunAsAny
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  fsGroup:
    rule: RunAsAny
