apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: default-restore-job-psp
  labels:
    app: stash
spec:
  privileged: false
  allowPrivilegeEscalation: false
  volumes:
  - "*" # restore job require to access all types of volume as user may use any volume
  hostNetwork: false
  hostIPC: false
  hostPID: false
  runAsUser:
    rule: RunAsAny
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  fsGroup:
    rule: RunAsAny
